# Makefile.in generated by automake 1.16.1 from Makefile.am.
# bibles/Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2018 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# Installing the pre-existing Bibles that are needed for the Bibledit Analysis window
# Thanks to https://xaizek.github.io/2014-09-28/how-to-install-data-directory-with-automake/


am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/bibledit-desktop
pkgincludedir = $(includedir)/bibledit-desktop
pkglibdir = $(libdir)/bibledit-desktop
pkglibexecdir = $(libexecdir)/bibledit-desktop
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-pc-linux-gnu
host_triplet = x86_64-pc-linux-gnu
target_triplet = x86_64-pc-linux-gnu
subdir = bibles
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/ax_cxx_compile_stdcxx.m4 \
	$(top_srcdir)/m4/ax_cxx_compile_stdcxx_11.m4 \
	$(top_srcdir)/m4/gettext.m4 $(top_srcdir)/m4/iconv.m4 \
	$(top_srcdir)/m4/intlmacosx.m4 $(top_srcdir)/m4/lib-ld.m4 \
	$(top_srcdir)/m4/lib-link.m4 $(top_srcdir)/m4/lib-prefix.m4 \
	$(top_srcdir)/m4/libtool.m4 $(top_srcdir)/m4/libxml2.m4 \
	$(top_srcdir)/m4/ltoptions.m4 $(top_srcdir)/m4/ltsugar.m4 \
	$(top_srcdir)/m4/ltversion.m4 $(top_srcdir)/m4/lt~obsolete.m4 \
	$(top_srcdir)/m4/nls.m4 $(top_srcdir)/m4/pkg.m4 \
	$(top_srcdir)/m4/po.m4 $(top_srcdir)/m4/progtest.m4 \
	$(top_srcdir)/acinclude.m4 $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(am__DIST_COMMON)
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
SOURCES =
DIST_SOURCES =
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
am__installdirs = "$(DESTDIR)$(bibles_byzascii_dir)" \
	"$(DESTDIR)$(bibles_engleb_dir)" \
	"$(DESTDIR)$(bibles_engmtv_dir)" \
	"$(DESTDIR)$(bibles_engnet_dir)" \
	"$(DESTDIR)$(bibles_sblapp_dir)" \
	"$(DESTDIR)$(bibles_sblgnt_dir)"
DATA = $(bibles_byzascii__DATA) $(bibles_engleb__DATA) \
	$(bibles_engmtv__DATA) $(bibles_engnet__DATA) \
	$(bibles_sblapp__DATA) $(bibles_sblgnt__DATA)
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
am__DIST_COMMON = $(srcdir)/Makefile.in
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
ACLOCAL = ${SHELL} /home/postiffm/bibledit/bibledit-desktop/missing aclocal-1.16
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 0
AR = ar
AUTOCONF = ${SHELL} /home/postiffm/bibledit/bibledit-desktop/missing autoconf
AUTOHEADER = ${SHELL} /home/postiffm/bibledit/bibledit-desktop/missing autoheader
AUTOMAKE = ${SHELL} /home/postiffm/bibledit/bibledit-desktop/missing automake-1.16
AWK = mawk
BIBLEDIT_LOCALEDIR = ${datarootdir}/locale
CAT_PATH = /bin/cat
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -ggdb -O2 
CYGPATH_W = echo
DATE_PATH = /bin/date
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = false
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
ENCHANT_CFLAGS = -pthread -I/usr/include/enchant -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
ENCHANT_LIBS = -lenchant
EXEEXT = 
FGREP = /bin/grep -F
FIND_CURL = /usr/bin/curl
FIND_DIFF = /usr/bin/diff
FIND_GPP = /usr/bin/g++
FIND_MERGE = /usr/bin/merge
FIND_PATCH = /usr/bin/patch
FIND_PATH = /usr/bin/find
FIND_TAR = /bin/tar
FIND_XARGS = /usr/bin/xargs
GETTEXT_MACRO_VERSION = 0.19
GETTEXT_PACKAGE = bibledit-desktop
GLIBMM_CFLAGS = -pthread -I/usr/include/giomm-2.4 -I/usr/lib/x86_64-linux-gnu/giomm-2.4/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glibmm-2.4 -I/usr/lib/x86_64-linux-gnu/glibmm-2.4/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/sigc++-2.0 -I/usr/lib/x86_64-linux-gnu/sigc++-2.0/include
GLIBMM_LIBS = -lgiomm-2.4 -lgio-2.0 -lglibmm-2.4 -lgobject-2.0 -lglib-2.0 -lsigc-2.0
GLIB_CFLAGS = -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
GLIB_LIBS = -lglib-2.0
GMSGFMT = /usr/bin/msgfmt
GMSGFMT_015 = /usr/bin/msgfmt
GOBJECT_CFLAGS = -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
GOBJECT_LIBS = -lgobject-2.0 -lglib-2.0
GREP = /bin/grep
GREP_PATH = /bin/grep
GTHREAD_CFLAGS = -pthread -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
GTHREAD_LIBS = -lgthread-2.0 -pthread -lglib-2.0
GTK3_CFLAGS = -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
GTK3_LIBS = -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0
GTKSOURCEVIEW_CFLAGS = -pthread -I/usr/include/gtksourceview-3.0 -I/usr/include/libxml2 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
GTKSOURCEVIEW_LIBS = -lgtksourceview-3.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0
GUNZIP_PATH = /bin/gunzip
GZIP_PATH = /bin/gzip
HAVE_CXX11 = 1
HEAD_PATH = /usr/bin/head
ICONV_PATH = /usr/bin/iconv
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
INTLLIBS = 
INTL_MACOSX_LIBS = 
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = 
LIBICONV = -liconv
LIBINTL = 
LIBOBJS = 
LIBS = 
LIBSOUP_CFLAGS = -pthread -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
LIBSOUP_LIBS = -lsoup-2.4 -lgio-2.0 -lgobject-2.0 -lglib-2.0
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBICONV = -liconv
LTLIBINTL = 
LTLIBOBJS = 
LT_SYS_LIBRARY_PATH = 
MAKEINFO = ${SHELL} /home/postiffm/bibledit/bibledit-desktop/missing makeinfo
MAKE_PATH = /usr/bin/make
MANIFEST_TOOL = :
MKDIR_P = /bin/mkdir -p
MSGFMT = /usr/bin/msgfmt
MSGFMT_015 = /usr/bin/msgfmt
MSGMERGE = /usr/bin/msgmerge
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = bibledit-desktop
PACKAGE_BUGREPORT = https://github.com/postiffm/bibledit-desktop
PACKAGE_NAME = bibledit-desktop
PACKAGE_STRING = bibledit-desktop 4.17
PACKAGE_TARNAME = bibledit-desktop
PACKAGE_URL = 
PACKAGE_VERSION = 4.17
PANGO_CFLAGS = -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
PANGO_LIBS = -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz
PATH_SEPARATOR = :
PKG_CONFIG = /usr/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = /usr/bin/pkg-config
POSUB = po
RANLIB = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/bash
SORT_PATH = /usr/bin/sort
SQLITE_CFLAGS = 
SQLITE_LIBS = -lsqlite3
STRINGS_PATH = /usr/bin/strings
STRIP = strip
TAIL_PATH = /usr/bin/tail
TEE_TOUCH = /usr/bin/touch
USE_NLS = yes
VERSION = 4.17
WEBKITGTK_CFLAGS = -pthread -I/usr/include/webkitgtk-4.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/webkitgtk-4.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
WEBKITGTK_LIBS = -lwebkit2gtk-4.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lsoup-2.4 -lgio-2.0 -ljavascriptcoregtk-4.0 -lgobject-2.0 -lglib-2.0
XGETTEXT = /usr/bin/xgettext
XGETTEXT_015 = /usr/bin/xgettext
XGETTEXT_EXTRA_OPTIONS = 
XML2_CONFIG = /usr/bin/xml2-config
XML_CPPFLAGS = -I/usr/include/libxml2
XML_LIBS = -lxml2
abs_builddir = /home/postiffm/bibledit/bibledit-desktop/bibles
abs_srcdir = /home/postiffm/bibledit/bibledit-desktop/bibles
abs_top_builddir = /home/postiffm/bibledit/bibledit-desktop
abs_top_srcdir = /home/postiffm/bibledit/bibledit-desktop
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = tar --format=ustar -chf - "$$tardir"
am__untar = tar -xf -
bindir = ${exec_prefix}/bin
build = x86_64-pc-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-pc-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/postiffm/bibledit/bibledit-desktop/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
packagedatadir = share/bibledit-desktop
pdfdir = ${docdir}
prefix = /home/postiffm/bibledit
program_transform_name = s,x,x,
psdir = ${docdir}
runstatedir = ${localstatedir}/run
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target = x86_64-pc-linux-gnu
target_alias = 
target_cpu = x86_64
target_os = linux-gnu
target_vendor = pc
top_build_prefix = ../
top_builddir = ..
top_srcdir = ..

# Destination directory
bibles_dir = $(pkgdatadir)/bibles
# Destination sub-directories
bibles_byzascii_dir = $(bibles_dir)/byzascii
bibles_sblgnt_dir = $(bibles_dir)/sblgnt
bibles_sblapp_dir = $(bibles_dir)/sblgnt
bibles_engleb_dir = $(bibles_dir)/engleb
bibles_engmtv_dir = $(bibles_dir)/engmtv
bibles_engnet_dir = $(bibles_dir)/engnet

# Files to install
bibles_byzascii__DATA = byzascii/1CO_BYZ.txt  byzascii/2CO_BYZ.txt  byzascii/3JO_BYZ.txt  byzascii/HEB_BYZ.txt \
			byzascii/MR_BYZ.txt   byzascii/RE_BYZ.txt   byzascii/1JO_BYZ.txt  byzascii/2JO_BYZ.txt \
			byzascii/AC_BYZ.txt   byzascii/JAS_BYZ.txt  byzascii/MT_BYZ.txt   byzascii/RO_BYZ.txt \
			byzascii/1PE_BYZ.txt  byzascii/2PE_BYZ.txt  byzascii/COL_BYZ.txt  byzascii/JOH_BYZ.txt \
			byzascii/PHM_BYZ.txt  byzascii/TIT_BYZ.txt  byzascii/1TH_BYZ.txt  byzascii/2TH_BYZ.txt \
			byzascii/EPH_BYZ.txt  byzascii/JUDE_BYZ.txt byzascii/PHP_BYZ.txt  byzascii/1TI_BYZ.txt \
			byzascii/2TI_BYZ.txt  byzascii/GA_BYZ.txt   byzascii/LU_BYZ.txt   byzascii/README

bibles_sblgnt__DATA = sblgnt/61-Mt.txt  sblgnt/62-Mk.txt  sblgnt/63-Lk.txt  sblgnt/64-Jn.txt \
			sblgnt/65-Ac.txt  sblgnt/66-Ro.txt  sblgnt/67-1Co.txt sblgnt/68-2Co.txt \
			sblgnt/69-Ga.txt  sblgnt/70-Eph.txt sblgnt/71-Php.txt sblgnt/72-Col.txt \
			sblgnt/73-1Th.txt sblgnt/74-2Th.txt sblgnt/75-1Ti.txt sblgnt/76-2Ti.txt \
			sblgnt/77-Tit.txt sblgnt/78-Phm.txt sblgnt/79-Heb.txt sblgnt/80-Jas.txt \
			sblgnt/81-1Pe.txt sblgnt/82-2Pe.txt sblgnt/83-1Jn.txt sblgnt/84-2Jn.txt \
			sblgnt/85-3Jn.txt sblgnt/86-Jud.txt sblgnt/87-Re.txt  sblgnt/license.txt

bibles_sblapp__DATA = sblgnt/61-Mt-APP.txt sblgnt/62-Mk-APP.txt sblgnt/63-Lk-APP.txt sblgnt/64-Jn-APP.txt \
			sblgnt/65-Ac-APP.txt sblgnt/66-Ro-APP.txt sblgnt/67-1Co-APP.txt sblgnt/68-2Co-APP.txt \
			sblgnt/69-Ga-APP.txt sblgnt/70-Eph-APP.txt sblgnt/71-Php-APP.txt sblgnt/72-Col-APP.txt \
			sblgnt/73-1Th-APP.txt sblgnt/74-2Th-APP.txt sblgnt/75-1Ti-APP.txt sblgnt/76-2Ti-APP.txt \
			sblgnt/77-Tit-APP.txt sblgnt/78-Phm-APP.txt sblgnt/79-Heb-APP.txt sblgnt/80-Jas-APP.txt \
			sblgnt/81-1Pe-APP.txt sblgnt/82-2Pe-APP.txt sblgnt/83-1Jn-APP.txt sblgnt/84-2Jn-APP.txt \
			sblgnt/85-3Jn-APP.txt sblgnt/86-Jud-APP.txt sblgnt/87-Re-APP.txt  sblgnt/license.txt

bibles_engleb__DATA = engleb/Gen.txt  engleb/Exo.txt  engleb/Lev.txt  engleb/Num.txt   engleb/Deut.txt engleb/Josh.txt engleb/Judg.txt \
			engleb/Ruth.txt engleb/1Sa.txt  engleb/2Sa.txt  engleb/1Ki.txt   engleb/2Ki.txt  engleb/1Ch.txt  engleb/2Ch.txt \
			engleb/Ezra.txt engleb/Neh.txt  engleb/Esth.txt engleb/Job.txt   engleb/Psal.txt engleb/Prov.txt engleb/Eccl.txt \
			engleb/Song.txt engleb/Isa.txt  engleb/Jer.txt  engleb/Lam.txt   engleb/Ezek.txt engleb/Dan.txt  engleb/Hos.txt \
			engleb/Joel.txt engleb/Amos.txt engleb/Obad.txt engleb/Jonah.txt engleb/Mic.txt  engleb/Nah.txt  engleb/Hab.txt \
			engleb/Zeph.txt engleb/Hag.txt  engleb/Zech.txt engleb/Mal.txt   engleb/Matt.txt engleb/Mark.txt engleb/Luke.txt \
			engleb/John.txt engleb/Acts.txt engleb/Rom.txt  engleb/1Co.txt   engleb/2Co.txt  engleb/Gal.txt  engleb/Eph.txt \
			engleb/Php.txt  engleb/Col.txt  engleb/1Th.txt  engleb/2Th.txt   engleb/1Tim.txt engleb/2Tim.txt engleb/Tit.txt \
			engleb/Phm.txt  engleb/Heb.txt  engleb/Jam.txt  engleb/1Pe.txt   engleb/2Pe.txt  engleb/1Jn.txt  engleb/2Jn.txt \
			engleb/3Jn.txt  engleb/Jude.txt engleb/Rev.txt

bibles_engmtv__DATA = engmtv/NewTestamentBibleworks.txt engmtv/NewTestamentOutline.txt \
			engmtv/1Co.txt  engmtv/2Th.txt  engmtv/Jam.txt \
			engmtv/1Jo.txt  engmtv/2Ti.txt  engmtv/Joh.txt engmtv/Phi.txt \
			engmtv/1Pe.txt  engmtv/3Jo.txt  engmtv/Jud.txt engmtv/Phm.txt \
			engmtv/1Th.txt  engmtv/Act.txt  engmtv/Luk.txt \
			engmtv/1Ti.txt  engmtv/Col.txt  engmtv/Mar.txt \
			engmtv/2Co.txt  engmtv/Eph.txt  engmtv/Mat.txt engmtv/Rev.txt \
			engmtv/2Jo.txt  engmtv/Gal.txt  engmtv/Rom.txt \
			engmtv/2Pe.txt  engmtv/Heb.txt  engmtv/Tit.txt

bibles_engnet__DATA = engnet/Gen.txt  engnet/Exo.txt  engnet/Lev.txt  engnet/Num.txt   engnet/Deut.txt engnet/Josh.txt engnet/Judg.txt \
			engnet/Ruth.txt engnet/1Sa.txt  engnet/2Sa.txt  engnet/1Ki.txt   engnet/2Ki.txt  engnet/1Ch.txt  engnet/2Ch.txt \
			engnet/Ezra.txt engnet/Neh.txt  engnet/Esth.txt engnet/Job.txt   engnet/Psa.txt  engnet/Prov.txt engnet/Eccl.txt \
			engnet/Song.txt engnet/Isa.txt  engnet/Jer.txt  engnet/Lam.txt   engnet/Ezek.txt engnet/Dan.txt  engnet/Hos.txt \
			engnet/Joel.txt engnet/Amos.txt engnet/Oba.txt  engnet/Jonah.txt engnet/Mic.txt  engnet/Nah.txt  engnet/Hab.txt \
			engnet/Zeph.txt engnet/Hag.txt  engnet/Zech.txt engnet/Mal.txt   engnet/Matt.txt engnet/Mark.txt engnet/Luke.txt \
			engnet/John.txt engnet/Acts.txt engnet/Rom.txt  engnet/1Co.txt   engnet/2Co.txt  engnet/Gal.txt  engnet/Eph.txt \
			engnet/Php.txt  engnet/Col.txt  engnet/1Th.txt  engnet/2Th.txt   engnet/1Tim.txt engnet/2Tim.txt engnet/Tit.txt \
			engnet/Phm.txt  engnet/Heb.txt  engnet/Jam.txt  engnet/1Pe.txt   engnet/2Pe.txt  engnet/1Jn.txt  engnet/2Jn.txt \
			engnet/3Jn.txt  engnet/Jude.txt engnet/Rev.txt

CLEANFILES = *~
all: all-am

.SUFFIXES:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      ( cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh ) \
	        && { if test -f $@; then exit 0; else break; fi; }; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu bibles/Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu bibles/Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__maybe_remake_depfiles)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__maybe_remake_depfiles);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(am__aclocal_m4_deps):

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs
install-bibles_byzascii_DATA: $(bibles_byzascii__DATA)
	@$(NORMAL_INSTALL)
	@list='$(bibles_byzascii__DATA)'; test -n "$(bibles_byzascii_dir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bibles_byzascii_dir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bibles_byzascii_dir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(bibles_byzascii_dir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(bibles_byzascii_dir)" || exit $$?; \
	done

uninstall-bibles_byzascii_DATA:
	@$(NORMAL_UNINSTALL)
	@list='$(bibles_byzascii__DATA)'; test -n "$(bibles_byzascii_dir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(bibles_byzascii_dir)'; $(am__uninstall_files_from_dir)
install-bibles_engleb_DATA: $(bibles_engleb__DATA)
	@$(NORMAL_INSTALL)
	@list='$(bibles_engleb__DATA)'; test -n "$(bibles_engleb_dir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bibles_engleb_dir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bibles_engleb_dir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(bibles_engleb_dir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(bibles_engleb_dir)" || exit $$?; \
	done

uninstall-bibles_engleb_DATA:
	@$(NORMAL_UNINSTALL)
	@list='$(bibles_engleb__DATA)'; test -n "$(bibles_engleb_dir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(bibles_engleb_dir)'; $(am__uninstall_files_from_dir)
install-bibles_engmtv_DATA: $(bibles_engmtv__DATA)
	@$(NORMAL_INSTALL)
	@list='$(bibles_engmtv__DATA)'; test -n "$(bibles_engmtv_dir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bibles_engmtv_dir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bibles_engmtv_dir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(bibles_engmtv_dir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(bibles_engmtv_dir)" || exit $$?; \
	done

uninstall-bibles_engmtv_DATA:
	@$(NORMAL_UNINSTALL)
	@list='$(bibles_engmtv__DATA)'; test -n "$(bibles_engmtv_dir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(bibles_engmtv_dir)'; $(am__uninstall_files_from_dir)
install-bibles_engnet_DATA: $(bibles_engnet__DATA)
	@$(NORMAL_INSTALL)
	@list='$(bibles_engnet__DATA)'; test -n "$(bibles_engnet_dir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bibles_engnet_dir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bibles_engnet_dir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(bibles_engnet_dir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(bibles_engnet_dir)" || exit $$?; \
	done

uninstall-bibles_engnet_DATA:
	@$(NORMAL_UNINSTALL)
	@list='$(bibles_engnet__DATA)'; test -n "$(bibles_engnet_dir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(bibles_engnet_dir)'; $(am__uninstall_files_from_dir)
install-bibles_sblapp_DATA: $(bibles_sblapp__DATA)
	@$(NORMAL_INSTALL)
	@list='$(bibles_sblapp__DATA)'; test -n "$(bibles_sblapp_dir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bibles_sblapp_dir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bibles_sblapp_dir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(bibles_sblapp_dir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(bibles_sblapp_dir)" || exit $$?; \
	done

uninstall-bibles_sblapp_DATA:
	@$(NORMAL_UNINSTALL)
	@list='$(bibles_sblapp__DATA)'; test -n "$(bibles_sblapp_dir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(bibles_sblapp_dir)'; $(am__uninstall_files_from_dir)
install-bibles_sblgnt_DATA: $(bibles_sblgnt__DATA)
	@$(NORMAL_INSTALL)
	@list='$(bibles_sblgnt__DATA)'; test -n "$(bibles_sblgnt_dir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bibles_sblgnt_dir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bibles_sblgnt_dir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(bibles_sblgnt_dir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(bibles_sblgnt_dir)" || exit $$?; \
	done

uninstall-bibles_sblgnt_DATA:
	@$(NORMAL_UNINSTALL)
	@list='$(bibles_sblgnt__DATA)'; test -n "$(bibles_sblgnt_dir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(bibles_sblgnt_dir)'; $(am__uninstall_files_from_dir)
tags TAGS:

ctags CTAGS:

cscope cscopelist:


distdir: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) distdir-am

distdir-am: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(DATA)
installdirs:
	for dir in "$(DESTDIR)$(bibles_byzascii_dir)" "$(DESTDIR)$(bibles_engleb_dir)" "$(DESTDIR)$(bibles_engmtv_dir)" "$(DESTDIR)$(bibles_engnet_dir)" "$(DESTDIR)$(bibles_sblapp_dir)" "$(DESTDIR)$(bibles_sblgnt_dir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-libtool mostlyclean-am

distclean: distclean-am
	-rm -f Makefile
distclean-am: clean-am distclean-generic

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-bibles_byzascii_DATA \
	install-bibles_engleb_DATA install-bibles_engmtv_DATA \
	install-bibles_engnet_DATA install-bibles_sblapp_DATA \
	install-bibles_sblgnt_DATA

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am:

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-generic mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-bibles_byzascii_DATA \
	uninstall-bibles_engleb_DATA uninstall-bibles_engmtv_DATA \
	uninstall-bibles_engnet_DATA uninstall-bibles_sblapp_DATA \
	uninstall-bibles_sblgnt_DATA

.MAKE: install-am install-strip

.PHONY: all all-am check check-am clean clean-generic clean-libtool \
	cscopelist-am ctags-am distclean distclean-generic \
	distclean-libtool distdir dvi dvi-am html html-am info info-am \
	install install-am install-bibles_byzascii_DATA \
	install-bibles_engleb_DATA install-bibles_engmtv_DATA \
	install-bibles_engnet_DATA install-bibles_sblapp_DATA \
	install-bibles_sblgnt_DATA install-data install-data-am \
	install-dvi install-dvi-am install-exec install-exec-am \
	install-html install-html-am install-info install-info-am \
	install-man install-pdf install-pdf-am install-ps \
	install-ps-am install-strip installcheck installcheck-am \
	installdirs maintainer-clean maintainer-clean-generic \
	mostlyclean mostlyclean-generic mostlyclean-libtool pdf pdf-am \
	ps ps-am tags-am uninstall uninstall-am \
	uninstall-bibles_byzascii_DATA uninstall-bibles_engleb_DATA \
	uninstall-bibles_engmtv_DATA uninstall-bibles_engnet_DATA \
	uninstall-bibles_sblapp_DATA uninstall-bibles_sblgnt_DATA

.PRECIOUS: Makefile


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
